// tracing is a wit interface that allows for an application to produce traces
// from within the guest. The interface supports being a tracing-provider (providing
// span resources to the guest from the host), or being a tracing-sink (recieving whole-spans
// from the guest)
interface tracing {
  // Common

  resource span {
    close: func();
  }

  /// Enter a named top-level span.
  ///
  /// Communicate to the o11y host that the guest is moving into a new span.
  span-enter: func(name: string) -> span;
}